$ANSIBLE_VAULT;1.1;AES256
30663162346430313936333232646463613866636239636562616666313738666331346164323130
3532383261663261366664643465613965393661316635650a353630343035313163333561636164
65616139313535626135306632633565636565396634616662633030373461376332386234376134
6637396431646565360a326438623566616137326436323164343232336435316162333361306166
33383739316561336661623730386234343636386233326233623261653365346636636562643133
38646363383737626532663336303361636636356233366265396131393836623131343035323866
66373661636239623161346632616264326631386662353939653832366335626430623865333834
31356635663763653661
